### ISSUE TITLE
Heart "Shards" and Unlocking the Lobby's Heart

### ISSUE THREAD

**Issue by GreyMario** [EverestAPI/CelesteCollabUtils2#14]
In short, each difficulty level has a set of "heart shards" obtained by completing each map in that difficulty. Collecting the full set spawns the lobby's Heart Gem.

Internally, the heart shards can be tracked as "heart gems" for the difficulty level's internal levelset. They don't have to be, but they *can* be. (Unless we can show a completion state on the Chapter Card somehow..?)

When collected, the heart shard will play its own custom cutscene, somewhat similar to a Summit Gem at the start. Summit Gem related sounds can be played during this cutscene.

A step by step progression of the cutscene:
- The Heart Shard breaks and is "absorbed" to Madeline as Summit Gems/Heart Gems do.
- Fade the screen, except Madeline, to full black, while performing the Heart Gem collection slowdown and freeze.
- Stop the level timer; **the level is technically complete now**.
- Probably enable skipping the cutscene via the menu at this point; it can get a little long from here.
- Move the camera up so that Madeline visually leaves the bottom of the screen.
- **If the level was already completed,** end the cutscene and level now.
- Display the progress made on collecting Heart Shards.
  - Show orbiting small Heart Shards, or their outline placeholders, around the outline of a Heart Gem.
  - Move a small Heart Shard in from the bottom of the screen and slot it into the appropriate outline placeholder.
- **If the collection is not yet complete,** end the cutscene and level on player input.
- On completion of the collection, accelerate the orbiting of the heart shards similarly to StrawberrySeed cutscene.
- One at a time, send Heart Shards to center of Heart Gem outline. The time it takes for this step to complete should be constant, regardless of the number of Heart Shards (five shards should take the same time to merge as fifty).
- Show the Heart Gem, including its heartbeat effect.
- End the cutscene and level on player input.

Similarly, **before the Heart Gem in the lobby has been spawned**, provide a visual of the progression at the Heart Gem's spawning location, using orbiting small Heart Shards/their outline placeholders. (This is also the object that *spawns* the Heart Gem.)

**Comment by maddie480** [comment]
#17 added mini hearts, #21 added a heart gate that opens with a cutscene when all mini hearts are collected, so this part can be considered done (even if the plans about that changed quite a bit... notably, heart sides are now a thing).
