### ISSUE TITLE
Rainbow Berry

### ISSUE THREAD

**Issue by Vexatos** [EverestAPI/CelesteCollabUtils2#6]
... or heart or some cool collectible that only appears if you collect ALL silver berries

*Migrated from iamdadbod's wishlist.*

**Comment by maddie480** [comment]
To-do list:
- [x] Have the rainbow berry spawn only when all silver berries in the associated level set are collected
- [x] Give the rainbow berry a custom sprite and collect sound
- [x] Implement custom "strawberry points" to replace 1000. Current plan is to make an animation saying "PERFECT" (in progress on branch rainbow_berry_perfect, mainly waiting for an animation to implement)
- [x] Have some kind of hologram or something where the rainbow berry _will_ be if it didn't spawn yet.
- [ ] Have an unlock animation when coming back to the lobby with all silvers, much like the heart side unlock cutscene. It would look like the strawberry seed cutscene for example
