### ISSUE TITLE
French Localization of CollabUtils2

### ISSUE THREAD

**Issue by Tomygood** [EverestAPI/CelesteCollabUtils2#86]
Hiya! With the release of the Strawberry Jam's french localization having been released in its latest patch, we (the sj french localization team) have made a French.txt file for CollabUtils2.

If possible, we would like to have it included in the next CollabUtils2 patch, so that french players can enjoy a fully localized strawberry jam experience 😃

[Here](https://pastebin.com/S3K1gagb) is the aforementioned French.txt, which includes all of the original dialogue translated (all of which has been tested and displays correctly in-game).

**Comment by maddie480** [comment]
There was a French translation at some point (because I'm French myself), and I couldn't come up with a translation for "speed berry" that doesn't sound ridiculous so I gave up :p 

I'm going to integrate that in the next version, what are the credits?

**Comment by Tomygood** [comment]
> There was a French translation at some point (because I'm French myself), and I couldn't come up with a translation for "speed berry" that doesn't sound ridiculous so I gave up :p
> 
> I'm going to integrate that in the next version, what are the credits?

Even though we were three to work on sj localization, I'm the only one who actually worked on translating CollabUtils2 so you can credit me I suppose :) ("Tomygood")

Also feel free to tell me if you have any changes in mind since you're French!
